---
apiVersion: v1
kind: Pod
metadata:
  name: kubedoom
  namespace: kubedoom
  labels:
    app: kubedoom
spec:
  containers:
  - image: storaxdev/kubedoom:0.5.0
    name: kubedoom
    ports:
    - containerPort: 5900 
      protocol: TCP 
  hostNetwork: true
  serviceAccountName: kubedoom
